//
// Created by Daniel Slade on 11/23/2022.
//

#ifndef INTERPRETER_TOKENTYPE_H
#define INTERPRETER_TOKENTYPE_H

#include <unordered_set>

enum TokenType {INVALID, EQUAL, EQUALEQUAL, NOTEQUAL, LESSTHAN, MORETHAN, LESSEQUALS, MOREEQUALS, AND, OR, PLUS, MINUS, TIMES, DIVIDE, MOD, NOT, PRINT, INPUT, IF, ELSE, WHILE, FOR, LBRACE, RBRACE, LPAREN, RPAREN, SEMICOLON, INT, STR, NAME, INTVAR, STRVAR};

#endif //INTERPRETER_TOKENTYPE_H
